-- Local/dev seed data only. Never applied to the production database by
-- `supabase db push`. The real built-in exercise catalog now lives in
-- migration 20260826100001_builtin_exercises.sql (applied here too, since
-- db:test/local dev apply every migration) -- nothing exercise-related
-- needs to be seeded separately any more.
